config/routes.rb
Rails.application.routes.draw do
  post "/addfriend", to: "order_members#create"

  
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end
  # authenticated :user do
  #   root 'home#index', as: 'authenticated_root'
  # end


  
  resource :friends
  resources :groups do
    post 'getName'
    post 'addFriend'
    delete 'deletefriend'
end

  get 'orders_details/index'
  resource :friends
  
  resources :orders do
    resources :orders_details
  end
 
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"




end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    before_action :authenticate_user!

    def new
		@friend_to_user = current_user.friends
	end
	
	def create
		@parameter = params[:email]
		
		if  @parameter.empty?
			@error_null = {'value': 'You have to enter some data'}
			render json: @error_null
		else 
            if User.exists? email: @parameter              	
                if @parameter == current_user.email 
                    @error_addSelf = {'same': 'You can not add your self !'}
                    render json: @error_addSelf
                else
                    @fid = User.find_by(email: params[:email])
                    @user = current_user
                    if @user.friendships.exists? friend_id: @fid.id
                        @error_addExist = {'exist': 'You already added this friend !'}
                        render json: @error_addExist
                    else
                        @user = current_user
                        @friend = Friendship.create(user_id: current_user.id, friend_id: @fid.id)
                        render json: @fid
                    end					
                end
            else
                @error_notValid = {'notValid': 'This user is not exist !'}
                render json: @error_notValid				
            end	
		end
			
	end 

	def show
        @friend_to_user = current_user.friends
	end

	def destroy
		@friend = Friendship.find_by(user_id: current_user.id,friend_id: params[:param2])
		@friend.destroy
        @friend_to_user = current_user.friends
		render :show
        # redirect_to root_path
	end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<div class="container">
  <div class="row">
		<label class="control-label col-sm-3">Friend Email</label>
		<input type="text" class="friendEmail col-sm-3" id="friendEmail">
	   <button class="addFriend btn btn-primary col-sm-3 ">Add</button>
  </div>	
</div>

app/views/friends/new.html.erb
<h1 style="color:#dc3b45;padding-top:20px" %>Add Friends</h1>
<p id="error_null" class="col-sm-12" style='color:red;'></p>
<%= render 'form' %>
<br>
<div class=" col-sm-4">
	<%= link_to "Show All Friends" , friends_path,class: "dropdown-item" %>
</div>

<br>

 <%= render :template => 'friends/show' %> 


<script type="text/javascript">

////////////////////////// add friend /////////////////////////////////
$('.addFriend').click(function(e){
	var email = jQuery('.friendEmail').val()
	console.log(email);	
	$.ajax({
        url: "/friends",
        method: 'POST',
        data: {
            email: email,
        },
        success: function(response) {    
       
      if (typeof response.value === 'undefined'){
         document.getElementById('friendEmail').value=""
        if(typeof response.notValid === 'undefined'){
        
          $('#error_null').empty();  
          if (typeof response.same === 'undefined'){

             if (typeof response.exist === 'undefined'){
              $('.fr_row').append(
                "<div class='col-sm-6'><div class='panel-success'><div class='textDesc row'><div class='col-sm-4'><h4 id='head_col'>"+response.email+"</h4></div><div class='col-sm-4'><a id='fr"+response.id+"' onclick='delete_friend("+response.id+")'>Unfriend</a></div></div></div></div>"	
                  );
              }else{ 
                $('#error_null').empty();  
                $('#error_null').append("<strong> * "+response.exist+"</strong>");  
              }
          }else{
              $('#error_null').empty();  
              $('#error_null').append("<strong> * "+response.same+"</strong>");  
          };
        }else{
           $('#error_null').empty();  
           $('#error_null').append("<strong> * "+response.notValid+"</strong>");  
        }  
      }else{ 
          $('#error_null').empty();  
           
          $('#error_null').append("<strong> * "+response.value+"</strong>");  
          };

      console.log(response);
      },
          error: function(xmlHttpRequestObj, status, error) {
            console.log(error);
          },
          complete: function(xmlHttpRequestObj) {
            console.log("complete");
          },
    
          async: true
    });
}); 

////////////////////////// delete friend /////////////////////////////////
function delete_friend(element){
    $fId = element;
    var confirm_delete = confirm("Are you sure you want to remove this friend?")
    if (confirm_delete){
        $.ajax({
            url: "/friends/",
            method: 'DELETE',
            data: {
                param2: $fId
            },
               success: function(response) {
                  console.log("friend has been deleted successfully");
                  document.getElementById('fr'+$fId).parentNode.parentNode.remove(); 
        }
    })
  }
}

</script>

app/views/friends/show.html.erb
<div>
<h2 style="padding: 22px;"> Friends </h2>
</div>

<div class="container col-sm-offset-1 col-sm-12" style="border: 2px solid black;border-radius: 16px;padding: 17px;">
	<div class="panel panel-danger">
  		<div class="panel-heading"><h4>Friends List</h4></div>
      <hr>
  		<div class="panel-body">
  	
  			<div class="fr_row row">
              <% @friend_to_user.each do |friend| %>
					<div class="col-sm-6">
						<div class="panel-success">
							<div class="textDesc row">
							   
								<h4  id='head_col' class="col-sm-6"><%= friend.email %></h4>
								<%= link_to 'Unfriend', 
									friends_path(:param2 => friend.id),
											method: :delete,
											data: { confirm: 'Are you sure you want to delete friend?' } %>
							</div>
						</div>
			    	</div>
			 <%end%>
  			</div>	

  		</div>
  	</div>	
</div>
 