config/routes.rb
Rails.application.routes.draw do
  post "/addfriend", to: "order_members#create"

  
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end
  # authenticated :user do
  #   root 'home#index', as: 'authenticated_root'
  # end


  
  resource :friends
  resources :groups do
    post 'getName'
    post 'addFriend'
    delete 'deletefriend'
end

  get 'orders_details/index'
  resource :friends
  
  resources :orders do
    resources :orders_details
  end
 
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"




end

app/models/group.rb
class Group < ApplicationRecord
    # belongs_to :user
    # has_many :group_members, :dependent => :delete_all

    has_many :group_members
    has_many :users, through: :group_members , dependent: :delete_all
end


  

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def new
		@group = current_user.groups
	end

	def create
        @group_params = params[:name]
		#check if the value is null
		if @group_params.empty?
			@error_null = {'value': 'You have to put some data in group name'}
			render json: @error_null
		else
			#if the name exist	
			if Group.exists? name: @group_params
				@error_exist = {'exist': 'This Group Name is already exist , please change the name'}
				render json: @error_exist
			else
				#it is new group
				@user = current_user
				@group = @user.groups.create(name: @group_params )		
				render json: @group
			end
		end
	end 

	def show
		@group = current_user.groups
	end

	def destroy
		@group = Group.find(params[:id])
		@group.destroy
		@group = current_user.groups
        render :show
		# redirect_to :back
	end


	def getName
		@group = Group.find(params[:id])
		@group_members =[]
		@group.group_members.each do |member|
			@group_members.push(User.find(member.user_id));
		end
	 	@group_data = {name: @group.name , members: @group_members}
		render json: @group_data
	end

	def addFriend
		@friendEmail = params[:email]	
			#check if it is null
		if @friendEmail.empty?
			@error_null = {'nullValue': 'Please insert some data !'}
			render json: @error_null
		else
			#check if it is wrong type
			if User.exists? email: @friendEmail
			#check if he add himself
			if @friendEmail == current_user.email	
				@error_addSelf = {'same': 'You can not add your self !'}
				render json: @error_addSelf
			  else	
			#check if the user exist in the group itself before
				@fid = User.find_by(email: params[:email])
				@current_group = Group.find(params[:groupId])
				if @current_group.group_members.exists? user_id: @fid.id  	  
					@error_addExist = {'addExist': 'This user is already assigned to this group !'}
					render json: @error_addExist
				else
					#check if this user in friendship list or not
					@fid = User.find_by(email: params[:email])
					@user = current_user
					if @user.friendships.exists? friend_id: @fid.id
					@fid = User.find_by(email: params[:email])
					@gid = params[:groupId]
					@group = @fid.group_members.create(group_id: @gid)
					render json: @fid
				    else
					@error_notFriend = {'notFriend': 'This user is not currently in your friend list!'}
					render json: @error_notFriend				    	
				    end
				end					
				
			
			end	
			else
			#it is a robot
			@error_notExist = {'notExist': 'This user is not exist !'}
			render json: @error_notExist
			end	
		end		
		
	
	end #function 

	def deletefriend
		@friend = User.find_by(id: params[:friendId])
		@group_member = GroupMember.find_by(group_id: params[:groupId],user_id: params[:friendId])
		@group_member.destroy
		render json: @friend
	end

	private
	def group_params
		params.require(:group).permit(:name)
	end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for :group, url: groups_path, html: {id: 'formGroup'}, remote: true do |f| %>
 
<div class="row">
	<div class="form-group col-sm-4">
	  <div class="row">
		<label class="control-label col-sm-5">Group Name</label>
		<input type="text" id="groupName" class="groupName col-sm-6">
		</div>
	</div>
	<div class="form-group col-sm-6">
		<button class="addGroupName btn btn-primary col-sm-offset-2 col-sm-3">create group</button>   
    </div>
</div>
<% end %>

app/views/groups/new.html.erb
<h1><code>Add New Group</code></h1>
            <!-- Errors -->
        <strong id="error_null" class="col-sm-offset-2 col-sm-8" style='color:red;'></strong>
        <!-- Errors -->
<%= render 'form' %>

<br>
<div class=" col-sm-4">
   <a href="/groups/show" class= "dropdown-item">Show All Groups</a>
</div>
<br>
<div class="row col-sm-12">

  <div class=" col-sm-offset-0.5 col-sm-5">
    <div class="panel panel-danger">
    <div class="panel-heading"><h4>My Groups</h4></div>
    <div class="panel-body">
        <table class="table table-hover">
            <thead>
                  <tr>
                    <th>Group Name</th>
                    <th colspan="2">Actions</th>
                  </tr>
            </thead>
            <tbody id="table" class="table_row">
              <% @group.each do |groups| %>
              <tr>
                <td><%= groups.name %></td>
                <td><a id="<%= groups.id %>" onclick='addGroupMembers(<%= groups.id %>)'>Add Members</a></td>
                <td><a id="grp<%= groups.id %>" onclick='delete_group(<%= groups.id %>)'>remove</a></td>
            </tr>
            <% end %>
            </tbody>
        </table>  			
      </div>
    </div>
  </div>  


  <div class=" col-sm-6" id="friend">
    <div class="panel panel-danger" style="
    border: 1px solid black;
    border-radius: 20px;
    padding: 25px;
    margin-left: 23px;
"> 
      <div class="panel-heading"><h4 id="gName"></h4></div>
        <div class="panel-body">

          <div id="error_null2" class="col-sm-offset-4 col-sm-8"></div><br>
          <%= render 'friends/form' %>

          <br> <hr>
          <!-- The Div that show friends of that group -->
          <div class="row gmembers">

          </div>
          <!-- End Of the show -->
        </div>
      </div>
  </div>
</div>

<script type="text/javascript">

document.getElementById('friend').style.visibility = 'hidden';

//////////////////////// add new group //////////////////
$('.addGroupName').click(function(e){
	
  var name = jQuery('.groupName').val()
	console.log(name);
  	$.ajax({
        url: "/groups",
        method: 'POST',
        data: {
            name: name,
        },
        success: function(response) {
        if (typeof response.value === 'undefined'){

          if (typeof response.exist === 'undefined'){
            $('.table_row').append(
              "<tr><td>"+response.name+"</td><td><a id="+response.id+" onclick='addGroupMembers("+response.id+")'>Add Members</a></td><td><a id='grp"+response.id+"' onclick='delete_group("+response.id+")'>remove</a></td></tr>"	
              );
              $('#error_null').empty(); 
              document.getElementById('groupName').value=""
          }else{ 
              $('#error_null').empty();  
              $('#error_null').append("<strong> * "+response.exist+"</strong>");  
          }
      }else{ 
          $('#error_null').empty();  
          $('#error_null').append("<strong> * "+response.value+"</strong>");  
      };

      console.log(response);
         
      },
      error: function(xmlHttpRequestObj, status, error) {
        console.log(error);
      },
      complete: function(xmlHttpRequestObj) {
        console.log("complete");
      },
    
          async: true
    });

});

////////////////////////// delete group /////////////////////////////////
function delete_group(element){
    $gId = element;
    var confirm_delete = confirm("Are you sure you want to remove this group?")
    if (confirm_delete){
        $.ajax({
            url: "/groups/"+$gId,
            method: 'DELETE',
            data: {
                id: $gId
            },
               success: function(response) {
                  console.log("group has been deleted");
                  document.getElementById('grp'+$gId).parentNode.parentNode.remove(); 
                  document.getElementById('friend').style.visibility = 'hidden';
                  <%
=begin%>
 $members=addGroupMembers($gId);
                  console.log($members)
                  document.getElementById('fr'+$members.id).parentNode.parentNode.remove(); 
<%
=end%>

        }
    })
  }
}

/////////////////////// add new friend to group ////////////////////////////
$('.addFriend').click(function(e){
  var email = jQuery('.friendEmail').val();
  console.log(email);
  $.ajax({
      url: "/groups/"+$gId+"/addFriend",
      method: 'POST',
      data:{
        groupId: $gId,
        email: email,
      },
      success: function(friend) {
        if (typeof friend.nullValue === 'undefined') {

          if(typeof friend.notExist === 'undefined') {

              if(typeof friend.addExist === 'undefined') {

                if(typeof friend.notFriend === 'undefined') {

                  if(typeof friend.same === 'undefined') {
                    $('#error_null2').empty();  
                    $('.gmembers').append(
                    "<div class='col-sm-12'><div class='panel-success deleteFriend'><div class='textDesc row'><div class='col-sm-6'><h4 id='head_col'>"+friend.email+"</h4></div><div class='col-sm-6'><a onclick='removeFriend("+friend.id+")' id='fr"+friend.id+"'>Remove</a></div></div></div></div>"  
                      );
                  }else{
                    $('#error_null2').empty();  
                    $('#error_null2').append("<strong style=color:red;> * "+friend.same+"</strong>");
                  }           
                }else{ //if it is not a friend
                  $('#error_null2').empty();  
                  $('#error_null2').append("<strong style=color:red;> * "+friend.notFriend+"</strong>");
                }          
              }else{ //if it is already assigned to the group
                $('#error_null2').empty();  
                $('#error_null2').append("<strong style=color:red;> * "+friend.addExist+"</strong>");
              }                
          }else{//if not valid
            $('#error_null2').empty();  
            $('#error_null2').append("<strong style=color:red;> * "+friend.notExist+"</strong>");
          }                                          
        }else{//if no null
          $('#error_null2').empty();  
          $('#error_null2').append("<strong style=color:red;> * "+friend.nullValue+"</strong>");
        }
      },
      error: function(xmlHttpRequestObj, status, error) {
          console.log(error);
      },
      complete: function(xmlHttpRequestObj) {
        console.log("complete");
      },
        async: true
      }); 
});

/////////////////////////// list all members of group
//////////////////// add group members ///////////////////////

function addGroupMembers(id){
  document.getElementById('friend').style.visibility = 'visible';     
	$gId = id;
	console.log($gId);	
	$.ajax({
        url: "/groups/"+$gId+"/getName",
        method: 'POST',
        data: {
            id: $gId,
        },
        success: function(response) {
           $('#gName').text(response.name);
          $('.gmembers').empty();
          $.each(response.members,function(key,value){
          $('.gmembers').append(
              "<div class='col-sm-12'><div class='panel-success deleteFriend'><div class='textDesc row'><div class='col-sm-6'><h4 id='head_col'>"+value.email+"</h4></div><div class='col-sm-6'><a onclick='removeFriend("+value.id+")' id='fr"+value.id+"'>Remove</a></div></div></div></div>"  
            );
          }); 
 
        },
        error: function(xmlHttpRequestObj, status, error) {
            console.log(error);
        },
        complete: function(xmlHttpRequestObj) {
            console.log("complete");
        },
        async: true
    });
	
}; 


//////////////// remove a friend ////////////////////////////
function removeFriend(elem){ 
  $fId = elem;
   var confirm_delete = confirm("Are you sure you want to remove this friend?")
    if (confirm_delete){
        $.ajax({
          url: "/groups/"+$gId+"/deletefriend",
          method: 'DELETE',
          data:{
            groupId: $gId,
            friendId: $fId,
          },
          success: function(response) {
              console.log("friend has been deleted");                   
              document.getElementById('fr'+$fId).parentNode.parentNode.remove(); 
          },
          error: function(xmlHttpRequestObj, status, error) {
              console.log(error);
          },
          complete: function(xmlHttpRequestObj) {
            console.log("complete");
          },
          async: true
        }); 
    }  
};

</script>

app/views/groups/show.html.erb
<div>
<h2 style="padding: 22px;"> Groups </h2>
</div>

<div class="col-sm-5">
	<div class="panel panel-danger">
  		<div class="panel-heading"><h4>My Groups</h4></div>
  		<div class="panel-body">
			
        <table class="table table-hover">
   			 <thead>
      				<tr>
        				<th>Group Name</th>
        				<th colspan="1">Actions</th>
      				</tr>
    		</thead>
    		<tbody id="table" class="table_row">
        		    <% @group.each do |groups| %>
      				<tr>
						<td><%= groups.name %></td>
                        <td><%= link_to 'remove', group_path(groups),
              					method: :delete,
              					data: { confirm: 'Are you sure you want to delete?' } %></td>	 

      					</tr>
      				<% end %>
    		</tbody>
  </table>  			
</div>
</div>