config/routes.rb
Rails.application.routes.draw do
  post "/addfriend", to: "order_members#create"

  
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end
  # authenticated :user do
  #   root 'home#index', as: 'authenticated_root'
  # end


  
  resource :friends
  resources :groups do
    post 'getName'
    post 'addFriend'
    delete 'deletefriend'
end

  get 'orders_details/index'
  resource :friends
  
  resources :orders do
    resources :orders_details
  end
 
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"




end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user, :class_name => "User",:optional => true
    has_many :user_order_joins    , dependent: :delete_all
    has_many :users, through: :user_order_joins  , dependent: :delete_all

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]



  def index
    @orders = Order.all
    @userOrder=UserOrderJoin.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
    @order=Order.find(params[:id])
    @order.update(status: 'finished')
    @order.users.each do |user|
      if user.id != @order.user_id
        @msg = current_user.full_name + ' marked his order ' + @order.orderType + ' as finished' 
        ActionCable.server.broadcast("notification_channel", { body: @msg, userId: user.id})
        @notificationDict  =  { :body => @msg, :user => user , :notificationType => "order finished",:seen => false}

        @notification = Notification.new(@notificationDict)
        @notification.save
      end
    end
    redirect_to orders_path
  end




  def create
  
    @order=Order.new
    @order.orderType=order_params[:orderType]
    @order.user_id=order_params[:user_id]
    @order.orderFrom=order_params[:orderFrom]
    @order.menuImage=order_params[:menuImage]
    @order.status="unfinished";
    notValidEmails=[]
    @order.save
    usersToAdd=order_params[:friendsToAdd].split(" ")
    
    usersToAdd.each do |user|
            @currentFriend=User.find_by(email:user)
      @dict  =  { :user =>@currentFriend , :order => @order}
      @userOrder=UserOrderJoin.new(@dict)
      @userOrder.save
    end
    @currentUser=User.find(order_params[:user_id])
    @dict  =  { :user =>@currentUser , :order => @order}
      @userOrder=UserOrderJoin.new(@dict)
      @userOrder.save

    uploaded_io = params[:order][:menuImage]
File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
  file.write(uploaded_io.read)
end
@order.menuImage=uploaded_io.original_filename

    respond_to do |format|
      if @order.save 
        @order.users.each do |user|
          if user.id != @order.user_id
            @msg = current_user.full_name + ' add you to his order ' + @order.orderType 
            ActionCable.server.broadcast("notification_channel", { body: @msg, userId: user.id})
            @notificationDict  =  { :body => @msg, :user => user , :notificationType => "add new order",:seen => false}
    
            @notification = Notification.new(@notificationDict)
            @notification.save
          end
        end
        format.html { redirect_to orders_path, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end


def update    
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.users.each do |user|
      if user.id != @order.user_id
        @msg = current_user.full_name + ' deleted his order ' + @order.orderType 
        ActionCable.server.broadcast("notification_channel", { body: @msg, userId: user.id})
        @notificationDict  =  { :body => @msg, :user => user , :notificationType => "order deleted",:seen => false}

        @notification = Notification.new(@notificationDict)
        @notification.save
      end
    end
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:orderType, :orderFrom, :menuImage,:user_id,:friendsToAdd)
    end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, class: "orderForm container")  do |form| %>
<% if order.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

    <ul>
        <% order.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group row">
    <label for="orderType" class="col-sm-2 col-form-label">Order type:</label>

    <%= form.select :orderType, ["Breakfast", "Lunch", "Dinner"], class: "form-control", :required => true %>
</div>


<div class="form-group row">
    <label for="orderFrom" class="col-sm-2 col-form-label">From:</label>

    <div class="col-sm-10">
        <%= form.text_field :orderFrom, :required => true, :required => true, class: "form-control", id: "orderFrom"  %>
    </div>
</div>



<div class="form-group row">
    <label for="menuImage" class="col-sm-2 col-form-label">Menu image</label>
    <div class="col-sm-10">
        <%= form.file_field :menuImage, accept: "image/x-png,image/gif,image/jpeg", :required => true%>
    </div>
</div>

<%= form.text_field :friendsToAdd, id:"friendsToAdd"+current_user.id.to_s ,  type: :hidden%>

<%= form.number_field :user_id ,id: :order_user_id,value:current_user.id ,type: :hidden%>




<div class="move" style="color:red ;position:absolute; top:350px">
    <%= form.submit %>
</div>


<% end %>



<div class="container">
    <form action="/addfriend" accept-charset="UTF-8" method="post" data-remote="true">

        <div class="form-group row">
            <label for="Email" class="col-sm-2 col-form-label">Enter a friend's email or group name: </label>
            <div class="col-sm-10">
                <input name="email" class="form-control" placeholder="group name must starts with #">
                <input class="btn btn-primary m-3" type="submit" name="commit" value="Add Friend">
                <span id=<%= "orderFriendsErrors"+current_user.id.to_s %>> </span>
            </div>
        </div>
    </form>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-striped text-center">
  <thead class="table-dark">
    <tr>
      <th>Order type</th>
      <th>Order from</th>
      <th>Menu image</th>
      <th>owner mail<th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
    
      <% order.users.each do |userInOrder|%>
       <%if userInOrder.id==current_user.id%>
      <tr>
        <td><%= order.orderType %></td>
        <td><%= order.orderFrom %></td>
    <td>
      <%= image_tag ("/uploads/"+order.menuImage ), class: "img-responsive" ,style: 'width:200px; height:100px'; %>
    </td>
        <td><%= order.user.email %></td>
        <td><%= link_to 'View', order_orders_details_path(order) %></td>
        <%if order.user_id==current_user.id%>
          <% if order.status == "unfinished" %>
            <td><%= link_to 'Finish', edit_order_path(order) %></td>
            <td><%= link_to 'Cancel', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
        <%end%>
        <%end%>
         <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path, class:"btn btn-primary float-right" %>

</div>

app/views/orders/new.html.erb
<div class="row">
    <div class="col">
        <%= render 'form', order: @order %>
    </div>
    <div id=<%= "orderFriends"+current_user.id.to_s %> class="col">

    </div>

</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ordertype:</strong>
  <%= @order.orderType %>
</p>

<p>
  <strong>Orderfrom:</strong>
  <%= @order.orderFrom %>
</p>

<p>
  <strong>Menuimage:</strong>
  <%= @order.menuImage %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>