config/routes.rb
Rails.application.routes.draw do
  post "/addfriend", to: "order_members#create"

  
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end
  # authenticated :user do
  #   root 'home#index', as: 'authenticated_root'
  # end


  
  resource :friends
  resources :groups do
    post 'getName'
    post 'addFriend'
    delete 'deletefriend'
end

  get 'orders_details/index'
  resource :friends
  
  resources :orders do
    resources :orders_details
  end
 
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/group.rb
class Group < ApplicationRecord
    # belongs_to :user
    # has_many :group_members, :dependent => :delete_all

    has_many :group_members
    has_many :users, through: :group_members , dependent: :delete_all
end


  

app/models/group_member.rb
class GroupMember < ApplicationRecord
    belongs_to :group
    belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
    belongs_to :user
  end
  

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user, :class_name => "User",:optional => true
    has_many :user_order_joins    , dependent: :delete_all
    has_many :users, through: :user_order_joins  , dependent: :delete_all

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :user_order_join
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_many :ownedOrders, :class_name => "Order", :foreign_key => 'user_id'
  has_many :user_order_joins
  has_many :orders, through: :user_order_joins
  has_many :orders
  has_many :user_order_joins
  has_many :order_details
  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create]

  has_many :friendships, :dependent => :delete_all
  has_many :friends, :through => :friendships
  has_many :groups, :dependent => :delete_all
  has_many :group_members, :dependent => :delete_all

  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable,

         # Add omniauthable and pass in which ever providers you are using here.
        #  :omniauthable, omniauth_providers:[:facebook, :github, :google_oauth2]
 
  devise :database_authenticatable,
         :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :github, :google_oauth2]
# Step Fifteen:
# Create and assign providers into table

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      puts "AAAAAAAAAAAAAAAAAAAAAAAAA"
      puts provider_data.info.inspect
      puts "xxxxxAAAAAAAAAAAAAAAAAAAAAAA"
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.image=provider_data.info.image
      user.full_name=provider_data.info.name
    end
  end



  # def self.connect_to_gmail(auth, signed_in_resource=nil)
  #   puts "------>>>>>" 
  #   puts auth.info
  #   puts "------<<<<<" 
  #   user = User.where(:provider => auth.provider, :uid => auth.uid).first
  #   if user
  #     return user
  #   else
  #     registered_user = User.where(:email => auth.info.email).first
  #     if registered_user
  #       return registered_user
  #     else
  #       user = User.create(
          
  #         provider:auth.provider, uid:auth.uid, email:auth.info.email,
  #         password:Devise.friendly_token[0,20],
  #       )
  #     end
  #   end
  # end

  

  # def avatar_from_provider

  def avatar_thumbnail
    if avatar.attached?
    avatar.variant(resize: "50x50!").processed
    else
      "/default_profile.jpg"
    end
  end

  private
  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'default_profile.jpg'
          )
        ),
        filename: 'default_profile.jpg',
        content_type: 'image/jpg'
      )
    end
  end

end

app/models/user_order_join.rb
class UserOrderJoin < ApplicationRecord
    belongs_to :user
    belongs_to :order
    has_many :order_detail
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index

  	if current_user
		@orders = Order.all.where(user_id: current_user.id).order(created_at: :desc) 
    @all = []
		current_user.friends.each { |fr|
			@all.push fr.orders
		}
		puts @all.inspect

	else
	redirect_to '/users/sign_in'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/order_members_helper.rb
module OrderMembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YallaNotlob</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="jquery/jquery.js"></script>


  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Yalla Notlob</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
           
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <% if current_user %>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to "Home" , home_index_path ,class: "nav-link active" %>
              </li>
              <li>
                 <a href="/friends/new" class= "nav-link active">Friends</a>
                </li>
                <li>
                  <a href="/groups/new" class= "nav-link active">Groups</a>
                 </li>
              <li class="nav-item">
                <a href="/orders" class= "nav-link active">Orders</a>
              </li>
            </ul>
            <% end %>

            <% if user_signed_in? %>
            <%= link_to 'logout', destroy_user_session_path, method: :delete, class:"m-1 btn btn-outline-danger" %>
            <% end %>


            <% if current_user %>
            <% if current_user.provider == "google_oauth2" || current_user.provider == "facebook" || current_user.provider == "github" %>
              <img src= '<%= current_user.image%>', style='height:50px;width:50px;margin-bottom:5px;'>

            <% else %>
              <%= image_tag(current_user.avatar_thumbnail) %>
            <%end%>
          <% end %>


          </div>
        </div>
      </nav>
      <% if user_signed_in? %>
        Welcome! <%= current_user.full_name %>
      <% end %>
      <% if notice.present? %>
      <p class="alert alert-primary"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
      
    </div>






 <% if user_signed_in? %>

        <div class="row ">
            <button style="display: none" id="<%= "notification"+current_user.id.to_s+"Trigger" %>" type="button" data-bs-toggle="modal" data-bs-target="<%= "#notification"+current_user.id.to_s+"Modal" %>" class="btn btn-success btn-sm">Add To Cart</button>


            <div class="modal fade" id="<%= "notification"+current_user.id.to_s+"Modal" %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">New Notification</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div id="<%= "notification"+current_user.id.to_s%>"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <%end %>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>


      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>